### ISSUE TITLE
No suitable driver Error

### ISSUE THREAD

**Issue by Fellow-Bennse** [penpot/penpot-helm#15]
Heya there!

trying to set up penpot in our Kubernetes and for some reason it fails to connect to our postgreSQL DB with:
java.sql.SQLException: No suitable driver (DriverManager.java:300)

Not a Java Dev myself (Python and DevOps mostly) and in terms of valid URL format and stuff I tried pretty much every format I know, always running into the same error however.

I used the example values.yaml file and adjusted it with our values. Just kinda stuck on that one.

Would appreciate some help (and maybe some format-information in the example file)

**Comment by bameda** [comment]
Hi @Fellow-Bennse 

some example could be:

```
config:
  postgresql:
    host: "my-postgresql.mycompany.com"     # or "10.0.0.1" or something similar
    port: 5432
    username: "penpot"
    password: "penpot"
    database: "penpot"
```

This will be interpolated, in the backend-deployment, as

```
          # (...)
          env:
            # (...)
            - name: PENPOT_DATABASE_URI
              value: "postgresql://my-postgresql.mycompany.com:5432/penpot"
            - name: PENPOT_DATABASE_USERNAME
              value: "penpot"
            - name: PENPOT_DATABASE_PASSWORD
              value: "penpot"
            # (...)
```

I hope this can help
