### ISSUE TITLE
Add existing secrets for appSecret & redisUri

### ISSUE THREAD

**Issue by K-MeLeOn** [penpot/penpot-helm#16]
I've modified the chart to use an existing `apiSecret` secrets and a new config `redisUri`.
I think this may be useful for some people, see the updated files below.

Here are the changes to the chart values:
<details>
<summary>values.yaml</summary>

```yaml
config:
  # -- The name of an existing secret.
  # @section -- Configuration parameters
  existingSecret: ""
  secretKeys:
    # -- The api secret key to use from an existing secret.
    # @section -- Configuration parameters
    apiSecretKey: ""

  redis:
    # -- The name of an existing secret.
    # @section -- Configuration parameters
    existingSecret: ""
    secretKeys:
      # -- The redis uri key to use from an existing secret. (redis://:password@host:port/database).
      # @section -- Configuration parameters
      redisUriKey: ""
```
</details>

Here are the changes made to the deployment files in the `templates` folder:
<details>
<summary>backend-deployment.yml</summary>

```yaml
            - name: PENPOT_SECRET_KEY
              {{- if not .Values.config.existingSecret }}
              value: {{ .Values.config.apiSecretKey | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret }}
                  key: {{ .Values.config.secretKeys.apiSecretKey }}
              {{- end }}

            # Redis connection settings
            - name: PENPOT_REDIS_URI
              {{- if not .Values.config.redis.existingSecret}}
              {{- if not .Values.config.redis.host }}
              value: {{ print "redis://" (include "penpot.fullname" .) "-redis-master:" .Values.config.redis.port "/" .Values.config.redis.database }}
              {{- else }}
              value: "redis://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}/{{ .Values.config.redis.database }}"
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.redis.existingSecret }}
                  key: {{ .Values.config.redis.secretKeys.redisUriKey }}
              {{- end }}
```
</details>

<details>
<summary>exporter-deployment.yml</summary>

```yaml
            - name: PENPOT_REDIS_URI
              {{- if not .Values.config.redis.existingSecret}}
              {{- if not .Values.config.redis.host }}
              value: {{ print "redis://" (include "penpot.fullname" .) "-redis-master:" .Values.config.redis.port "/" .Values.config.redis.database }}
              {{- else }}
              value: "redis://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}/{{ .Values.config.redis.database }}"
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.redis.existingSecret }}
                  key: {{ .Values.config.redis.secretKeys.redisUriKey }}
              {{- end }}
```
</details>

I hope it can help 👍
